import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header
          style={{
            padding: "20px 40px",
            borderBottom: "1px solid #eee",
            fontWeight: "bold",
            fontSize: "20px",
          }}
        >
          <a href="/" style={{ textDecoration: "none", color: "black" }}>
            Trust Travel
          </a>
        </header>

        <main>
          {children}
        </main>

      </body>
    </html>
  );
}