# Generated by Django 6.0.3 on 2026-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
