# Generated by Django 6.0.3 on 2026-03-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_experience_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
