# Generated by Django 6.0.3 on 2026-03-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_destination_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
