# Generated by Django 6.0.3 on 2026-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_place_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="title",
        ),
        migrations.AddField(
            model_name="experience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
