# Generated by Django 6.0.3 on 2026-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_experiencereply"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="trust_level",
            field=models.IntegerField(default=3),
        ),
    ]
