# Generated by Django 6.0.3 on 2026-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_experience_trust_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
