# Generated by Django 6.0.3 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
