# Generated by Django 6.0.3 on 2026-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_seenupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="title",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
