# Generated by Django 6.0.3 on 2026-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_experience_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="external_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="place",
            name="external_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
