# Generated by Django 6.0.3 on 2026-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_place_external_id_place_external_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="experience_images/"
            ),
        ),
    ]
