# Generated by Django 6.0.3 on 2026-05-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_experiencephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_updates",
                to="core.experience",
            ),
        ),
    ]
