# Generated by Django 6.0.3 on 2026-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_update_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="place_type",
            field=models.CharField(
                choices=[
                    ("country", "Country"),
                    ("city", "City / Region"),
                    ("attraction", "Tourist attraction"),
                    ("hotel", "Hotel"),
                    ("restaurant", "Restaurant / Café"),
                    ("nature", "Beach / Nature spot"),
                    ("other", "Other"),
                ],
                default="city",
                max_length=30,
            ),
        ),
    ]
