# Generated by Django 6.0.3 on 2026-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_place_place_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="event_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional date/time related to the event, alert or information.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="external_link",
            field=models.URLField(
                blank=True,
                help_text="Optional external link related to the update.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Optional source name, e.g. official website, local authority, venue page.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Optional source URL for verification.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Short title for event, alert or useful information.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="update",
            name="category",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("religious", "Religious"),
                    ("social", "Social"),
                    ("tourism", "Tourism"),
                    ("transport", "Transport"),
                    ("safety", "Safety"),
                    ("weather", "Weather"),
                    ("food", "Food"),
                    ("culture", "Culture"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
