# Generated by Django 6.0.3 on 2026-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_update_event_date_update_external_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("18_24", "18–24"),
                    ("25_34", "25–34"),
                    ("35_44", "35–44"),
                    ("45_54", "45–54"),
                    ("55_64", "55–64"),
                    ("65_plus", "65+"),
                ],
                default="prefer_not_to_say",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country_of_birth",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profile",
            name="country_of_residence",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profile",
            name="nationality",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_nationality",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="travel_context",
            field=models.CharField(
                choices=[
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("solo", "Solo traveler"),
                    ("couple", "Couple"),
                    ("family_children", "Family with children"),
                    ("friends_group", "Friends / group"),
                    ("business", "Business traveler"),
                    ("retired", "Retired traveler"),
                    ("local_resident", "Local resident"),
                ],
                default="prefer_not_to_say",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="travel_style",
            field=models.CharField(
                choices=[
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("culture_museums", "Culture and museums"),
                    ("nature_outdoors", "Nature and outdoors"),
                    ("food_restaurants", "Food and restaurants"),
                    ("relaxed", "Relaxed travel"),
                    ("budget", "Budget travel"),
                    ("comfort", "Comfort travel"),
                    ("adventure", "Adventure"),
                    ("local_life", "Local life"),
                ],
                default="prefer_not_to_say",
                max_length=30,
            ),
        ),
    ]
