# Generated by Django 6.0.3 on 2026-05-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_profile_age_range_profile_country_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="travel_context",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="travel_style",
        ),
    ]
