# Generated by Django 6.0.3 on 2026-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_profile_travel_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nationality_country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
