# Generated by Django 6.0.3 on 2026-05-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_profile_nationality_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="trip_context",
            field=models.CharField(
                choices=[
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("solo", "Solo traveler"),
                    ("couple", "Couple"),
                    ("family_children", "Family with children"),
                    ("friends_group", "Friends / group"),
                    ("business", "Business traveler"),
                    ("local_resident", "Local resident"),
                    ("retired", "Retired traveler"),
                ],
                default="prefer_not_to_say",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="trip_style",
            field=models.CharField(
                choices=[
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("culture_museums", "Culture and museums"),
                    ("nature_outdoors", "Nature and outdoors"),
                    ("food_restaurants", "Food and restaurants"),
                    ("relaxed", "Relaxed travel"),
                    ("budget", "Budget travel"),
                    ("comfort", "Comfort travel"),
                    ("adventure", "Adventure"),
                    ("local_life", "Local life"),
                ],
                default="prefer_not_to_say",
                max_length=30,
            ),
        ),
    ]
