# Generated by Django 6.0.3 on 2026-05-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_saveditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short name for this trip plan, e.g. Thailand 2027 or Weekend in Amsterdam.",
                        max_length=160,
                    ),
                ),
                (
                    "destination_text",
                    models.CharField(
                        blank=True,
                        help_text="Free text destination, e.g. Thailand, Rome, Amsterdam, Northeast Brazil.",
                        max_length=160,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="saveditem",
            name="unique_saved_experience_per_user",
        ),
        migrations.AddField(
            model_name="tripplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saveditem",
            name="trip_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_items",
                to="core.tripplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="saveditem",
            constraint=models.UniqueConstraint(
                fields=("trip_plan", "experience"),
                name="unique_experience_per_trip_plan",
            ),
        ),
    ]
