# Generated by Django 6.0.3 on 2026-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_tripplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profession",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_profile_context",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="travel_interests",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
