# Generated by Django 6.0.3 on 2026-05-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_profile_profession_profile_show_profile_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="recovery_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="recovery_code_hash",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
