# Generated by Django 6.0.3 on 2026-05-30 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_profile_recovery_code_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("experience", "Experience"),
                            ("update", "Update"),
                            ("place", "Place"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("misleading_information", "Misleading information"),
                            ("unsafe_place", "Unsafe place"),
                            ("fake_photo", "Fake photo"),
                            ("scam_or_fraud", "Scam or fraud"),
                            ("harassment", "Harassment"),
                            ("suspicious_behavior", "Suspicious behavior"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action taken"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.experience",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.place",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_content_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.update",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "reported_by",
                            "content_type",
                            "experience",
                            "update",
                            "place",
                        ),
                        name="unique_report_per_user_content",
                    )
                ],
            },
        ),
    ]
