# Generated by Django 6.0.3 on 2026-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_savedplace"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="destination",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_destination_name_country"
            ),
        ),
    ]
