# Generated by Django 6.0.3 on 2026-06-12 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_destination_unique_destination_name_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("destination", "name"), name="unique_place_name_per_destination"
            ),
        ),
    ]
