# Generated by Django 6.0.3 on 2026-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_tripplanactivityseen"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="accessibility_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="convenience_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="cost_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="safety_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
