# Generated by Django 6.0.3 on 2026-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_experience_accessibility_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="image_display_mode",
            field=models.CharField(
                choices=[("contain", "Full photo"), ("cover", "Fill frame")],
                default="cover",
                max_length=20,
            ),
        ),
    ]
