# Generated by Django 6.0.3 on 2026-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_experience_image_display_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="image_caption",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
