# Generated by Django 6.0.3 on 2026-06-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_experience_image_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="parent_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_places",
                to="core.place",
            ),
        ),
    ]
