# Generated by Django 6.0.3 on 2026-07-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_place_parent_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="place",
            name="canonical_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
