# Generated by Django 6.0.3 on 2026-07-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_placelocationsuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripPlanDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary destination"),
                            ("secondary", "Secondary destination"),
                        ],
                        default="secondary",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_plan_destinations",
                        to="core.place",
                    ),
                ),
                (
                    "trip_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="core.tripplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip_plan", "place"),
                        name="unique_destination_place_per_trip_plan",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "primary")),
                        fields=("trip_plan",),
                        name="unique_primary_destination_per_trip_plan",
                    ),
                ],
            },
        ),
    ]
