# Generated by Django 6.0.3 on 2026-08-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_tripplandestination"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
