# Generated by Django 6.0.3 on 2026-08-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_place_country_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("canonical_name", models.CharField(max_length=150, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["canonical_name"],
            },
        ),
        migrations.AddField(
            model_name="place",
            name="country_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="places",
                to="core.country",
            ),
        ),
    ]
