# Generated by Django 6.0.3 on 2026-08-24 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_backfill_place_country_refs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("external_source", ""), _negated=True),
                    models.Q(("external_id", ""), _negated=True),
                ),
                fields=("external_source", "external_id"),
                name="unique_place_external_identity",
            ),
        ),
    ]
