# Generated by Django 6.0.3 on 2026-09-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_tripplanresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local_authority", "Local authority"),
                            ("tourism_board", "Tourism board"),
                            ("transport_authority", "Transport authority"),
                            ("government_agency", "Government agency"),
                            ("venue", "Venue"),
                            ("official_organization", "Official organization"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_sources",
                        to="core.place",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="update",
            name="official_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional Trust Travel-recognized official source. This is separate from the user-provided source name and URL.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updates",
                to="core.officialsource",
            ),
        ),
    ]
