# Generated by Django 6.0.3 on 2026-09-06 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_officialsource_update_official_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialSourceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_url", models.URLField(blank=True, max_length=1000)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("ignored", "Ignored"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "official_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.officialsource",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_source_entries",
                        to="core.place",
                    ),
                ),
                (
                    "resulting_update",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_source_entry",
                        to="core.update",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-discovered_at", "-created_at"],
            },
        ),
    ]
