# Generated by Django 6.0.3 on 2026-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_officialsourceentry_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialsourceentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("religious", "Religious"),
                    ("social", "Social"),
                    ("tourism", "Tourism"),
                    ("transport", "Transport"),
                    ("safety", "Safety"),
                    ("weather", "Weather"),
                    ("food", "Food"),
                    ("culture", "Culture"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="officialsourceentry",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialsourceentry",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="officialsourceentry",
            name="update_type",
            field=models.CharField(
                choices=[("event", "Event"), ("alert", "Alert"), ("info", "Info")],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="officialsourceentry",
            name="title",
            field=models.CharField(max_length=160),
        ),
    ]
