# Generated by Django 6.0.3 on 2026-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_officialsourceentry_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Optional source name, e.g. official website, local authority, venue page.",
                max_length=160,
            ),
        ),
    ]
