# Generated by Django 6.0.3 on 2026-09-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_alter_update_source_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("official_name", models.CharField(blank=True, max_length=255)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unclaimed", "Unclaimed"),
                            ("claimed", "Claimed"),
                            ("suspended", "Suspended"),
                        ],
                        default="unclaimed",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_presence",
                        to="core.place",
                    ),
                ),
            ],
        ),
    ]
