# Generated by Django 6.0.3 on 2026-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_businessclaimrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessclaimrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
