# Generated by Django 6.0.3 on 2026-09-12 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_businesspresencelink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professional_name", models.CharField(max_length=160)),
                (
                    "professional_type",
                    models.CharField(
                        choices=[
                            ("travel_expert", "Travel expert"),
                            ("gastronomy_expert", "Gastronomy expert"),
                            ("journalist", "Journalist"),
                            ("guide", "Guide"),
                            ("photographer", "Photographer"),
                            ("creator", "Creator / Influencer"),
                            ("historian", "Historian"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_presence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
