# Generated by Django 6.0.3 on 2026-09-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_professionalpresence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalPresenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("portfolio", "Portfolio"),
                            ("newsletter", "Newsletter"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional_presence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_links",
                        to="core.professionalpresence",
                    ),
                ),
            ],
            options={
                "ordering": ["link_type", "created_at"],
            },
        ),
    ]
