# Generated by Django 6.0.3 on 2026-09-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_professionalpresencelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalBusinessRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("independent", "Independent"),
                            ("invited", "Invited"),
                            ("sponsored", "Sponsored"),
                            ("commercial_partnership", "Commercial partnership"),
                            ("ambassador", "Ambassador"),
                            ("employee", "Employee"),
                            ("owner", "Owner"),
                            ("other", "Other"),
                        ],
                        default="independent",
                        max_length=40,
                    ),
                ),
                ("disclosure_text", models.TextField(blank=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_presence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_relationships",
                        to="core.businesspresence",
                    ),
                ),
                (
                    "professional_presence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_relationships",
                        to="core.professionalpresence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=(
                            "professional_presence",
                            "business_presence",
                            "relationship_type",
                        ),
                        name="unique_current_professional_business_relationship",
                    )
                ],
            },
        ),
    ]
