# Generated by Django 6.0.3 on 2026-09-13 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_professionalbusinessrelationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("analysis", "Analysis"),
                            ("recommendation", "Recommendation"),
                            ("review", "Review"),
                            ("guide", "Guide"),
                            ("report", "Report"),
                            ("tip", "Tip"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions",
                        to="core.professionalbusinessrelationship",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_contributions",
                        to="core.place",
                    ),
                ),
                (
                    "professional_presence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="core.professionalpresence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
