# Generated by Django 6.0.3 on 2026-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_professionalevaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allow_level_2_experience_comments",
            field=models.BooleanField(default=False),
        ),
    ]
