# Generated by Django 6.0.3 on 2026-09-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_professionalfeedmute"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="gallery_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.experiencephoto",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="gallery_photo_source",
            field=models.CharField(
                blank=True,
                choices=[("main", "Main photo"), ("extra", "Extra photo")],
                max_length=10,
            ),
        ),
    ]
