# Generated by Django 6.0.3 on 2026-09-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_experience_gallery_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="gallery_featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
