# Generated by Django 6.0.3 on 2026-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_galleryseen"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="geographic_type",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
