# Generated by Django 6.0.3 on 2026-09-20 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_place_geographic_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="place",
            name="unique_place_name_per_destination",
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_source", ""), ("external_id", "")),
                fields=("destination", "name"),
                name="unique_legacy_place_name_per_destination",
            ),
        ),
    ]
