# Generated by Django 6.0.3 on 2026-09-21 18:01

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_place_external_identities(apps, schema_editor):
    Place = apps.get_model("core", "Place")
    PlaceExternalIdentity = apps.get_model(
        "core",
        "PlaceExternalIdentity",
    )

    places = (
        Place.objects
        .exclude(external_source="")
        .exclude(external_id="")
    )

    for place in places.iterator():
        geographic_type = ""

        if place.external_source == "geonames":
            geographic_type = place.geographic_type or ""

        PlaceExternalIdentity.objects.get_or_create(
            external_source=place.external_source,
            external_id=place.external_id,
            defaults={
                "place_id": place.id,
                "geographic_type": geographic_type,
            },
        )


def remove_copied_place_external_identities(apps, schema_editor):
    Place = apps.get_model("core", "Place")
    PlaceExternalIdentity = apps.get_model(
        "core",
        "PlaceExternalIdentity",
    )

    identities = (
        PlaceExternalIdentity.objects
        .select_related("place")
        .all()
    )

    for identity in identities.iterator():
        place = identity.place

        if (
            identity.external_source == place.external_source
            and identity.external_id == place.external_id
        ):
            identity.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_remove_place_unique_place_name_per_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_source", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=255)),
                ("geographic_type", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="core.place",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("external_source", "external_id"),
                        name="unique_place_external_identity_record",
                    )
                ],
            },
        ),
        migrations.RunPython(
            copy_existing_place_external_identities,
            remove_copied_place_external_identities,
        ),
    ]
