# Generated by Django 6.0.3 on 2026-09-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_placeexternalidentity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="place",
            name="unique_place_external_identity",
        ),
        migrations.RemoveConstraint(
            model_name="place",
            name="unique_legacy_place_name_per_destination",
        ),
        migrations.RemoveField(
            model_name="place",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="place",
            name="external_source",
        ),
    ]
